### ISSUE TITLE
Out of Memory

### ISSUE THREAD

**Issue by RajAre** [gcacace/android-signaturepad#93] opened 2017-08-17 04:28 UTC
Hi,

Getting the following error while capturing signature from my app. My app is using 1.2.0 v, trying to update with latest version but not seen any changes in ensureSignatureBitmap() method in latest 1.2.1 version also.  

Can some one give me guidance to resolve this issue from ui without waiting for fix from library. 

LOG: 

> at android.graphics.Bitmap.nativeCreate(Native Method)
>   at android.graphics.Bitmap.createBitmap(Bitmap.java:809)
>   at android.graphics.Bitmap.createBitmap(Bitmap.java:786)
>   at android.graphics.Bitmap.createBitmap(Bitmap.java:753)
>  at com.github.gcacace.signaturepad.views.SignaturePad.ensureSignatureBitmap(SignaturePad.java:573)
>  at com.github.gcacace.signaturepad.views.SignaturePad.addBezier(SignaturePad.java:461)
>  at com.github.gcacace.signaturepad.views.SignaturePad.addPoint(SignaturePad.java:439)
>  at com.github.gcacace.signaturepad.views.SignaturePad.onTouchEvent(SignaturePad.java:185)
>  at com.nyco.kiosk.ui.views.SignaturePadWithPointsCapture.onTouchEvent(SignaturePadWithPointsCapture.java:50)
>  at android.view.View.dispatchTouchEvent(View.java:7710)
>  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
>  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
>  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
>  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
>  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
>  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
>  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
>  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
>  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
>  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
>  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
>  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
>  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
>  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
>  at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2068)
>  at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1515)

**Comment by dskrvk** [comment] 2018-09-17 19:42
Duplicate of https://github.com/gcacace/android-signaturepad/issues/49?

**Closed** 2021-09-29 14:04 UTC
