### ISSUE TITLE
Transaction TooLarge Exception

### ISSUE THREAD

**Issue by das-10** [gcacace/android-signaturepad#153] opened 2020-06-08 16:59 UTC
the SignaturePad view cause Transaction TooLarge Exception.

How to reproduce the Exception:
navigate to the activity/fragment where the SignaturePad View is implemented.
just hide your app(Android os will call onSavedInstance)
you get the Exception throw.

I use Android  version 9.

**Comment by voghDev** [comment] 2020-06-11 14:16
Hi @das-10 !

I'm wondering if this exception appeared [after migrating to androidx](https://github.com/gcacace/android-signaturepad/pull/141). Can you downgrade your library version to the previous one, and check your App again to see if the Exception is gone?

thanks!

**Comment by ArthurNagy** [comment] 2020-06-17 12:22
Hey!
It's not a new issue introduced recently, there are duplicate issues for this: #114 and #97 
Take a look at the comment for a possible workaround and the state of the issue.

**Comment by voghDev** [comment] 2020-07-14 08:19
Ok. For those experiencing this issue, I suggest to temporarily downgrade from `1.3.1` to `1.2.1` while we discover a possible root cause of this error, which seems happening more often in `1.3.1` than previous versions

**Comment by oradkovsky** [comment] 2020-08-07 12:16
Problem with downgrading to 1.2.1 is lost state (when view recreates it's blank). I'm so far experimenting with these changes https://github.com/oradkovsky/android-signaturepad/tree/transactiontoolarge_exception_fix if anyone interested.

**Comment by Joe3112** [comment] 2021-02-22 12:51
A quick fix to this issue would be the following:

`class SignatureView @JvmOverloads constructor(
    context: Context, attrs: AttributeSet? = null, defStyleAttr: Int = 0
) : SignaturePad(context, attrs) {

    override fun onSaveInstanceState(): Parcelable? {
        super.onSaveInstanceState()
        return null
    }

    override fun onRestoreInstanceState(state: Parcelable?) {
        super.onRestoreInstanceState(state)
    }
}`

**Comment by ankurbhut** [comment] 2021-05-11 10:16
Use below property in your signature pad view and it will works in latest version also.

`android:saveEnabled="false" `

**Comment by gcacace** [comment] 2021-09-29 14:06
Duplicate of #49

**Closed by gcacace** 2021-09-29 14:06 UTC
