### ISSUE TITLE
java.lang.OutOfMemoryError: 

### ISSUE THREAD

**Issue by MattiaCaceffo** [gcacace/android-signaturepad#121] opened 2018-08-10 14:16 UTC
Hello, I've been using the library for a long time, but recently I've encountered problems:

**java.lang.OutOfMemoryError:** 
  at dalvik.system.VMRuntime.newNonMovableArray (Native Method)
  at android.graphics.Bitmap.nativeCreate (Native Method)
  at android.graphics.Bitmap.createBitmap (Bitmap.java:879)
  at android.graphics.Bitmap.createBitmap (Bitmap.java:856)
  at android.graphics.Bitmap.createBitmap (Bitmap.java:823)
  **at com.github.gcacace.signaturepad.views.SignaturePad.ensureSignatureBitmap (SignaturePad.java:573)
  at com.github.gcacace.signaturepad.views.SignaturePad.addBezier (SignaturePad.java:461)
  at com.github.gcacace.signaturepad.views.SignaturePad.addPoint (SignaturePad.java:439)
  at com.github.gcacace.signaturepad.views.SignaturePad.onTouchEvent (SignaturePad.java:185**)
  at android.view.View.dispatchTouchEvent (View.java:10062)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2782)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2422)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2782)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2422)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2782)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2422)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2782)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2422)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2782)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2422)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2782)
...etc

_with android 7.0_

AND:

**java.lang.OutOfMemoryError:** 
  at dalvik.system.VMRuntime.newNonMovableArray (Native Method)
  at android.graphics.Bitmap.nativeCreate (Native Method)
  at android.graphics.Bitmap.createBitmap (Bitmap.java:879)
  at android.graphics.Bitmap.createBitmap (Bitmap.java:856)
  at android.graphics.Bitmap.createBitmap (Bitmap.java:823)
  **at com.github.gcacace.signaturepad.views.SignaturePad.getSignatureBitmap (SignaturePad.java:232)
  at it.milkman.milkmandriver.SignActivity.askConsignee (SignActivity.java:106)
  at it.milkman.milkmandriver.SignActivity.access$300 (SignActivity.java:20)
  at it.milkman.milkmandriver.SignActivity$3.onClick (SignActivity.java:98)**
  at android.view.View.performClick (View.java:5637)
  at android.view.View$PerformClick.run (View.java:22433)
  at android.os.Handler.handleCallback (Handler.java:751)
  at android.os.Handler.dispatchMessage (Handler.java:95)
  at android.os.Looper.loop (Looper.java:154)
  at android.app.ActivityThread.main (ActivityThread.java:6123)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:889)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:779)

_with android 7.1 and 7.0_

thank you

**Comment by dskrvk** [comment] 2018-09-17 19:29
Duplicate of https://github.com/gcacace/android-signaturepad/issues/49?

**Closed** 2021-09-29 14:05 UTC
