### ISSUE TITLE
Gettinh OutOfMemory error

### ISSUE THREAD

**Issue by shadowTech827** [gcacace/android-signaturepad#83] opened 2017-05-15 10:21 UTC
E/UncaughtException: java.lang.OutOfMemoryError
                                                          at android.graphics.Bitmap.nativeCreate(Native Method)
                                                          at android.graphics.Bitmap.createBitmap(Bitmap.java:822)
                                                          at android.graphics.Bitmap.createBitmap(Bitmap.java:799)
                                                          at android.graphics.Bitmap.createBitmap(Bitmap.java:766)
                                                          at com.github.gcacace.signaturepad.views.SignaturePad.ensureSignatureBitmap(SignaturePad.java:393)
                                                          at com.github.gcacace.signaturepad.views.SignaturePad.addBezier(SignaturePad.java:282)
                                                          at com.github.gcacace.signaturepad.views.SignaturePad.addPoint(SignaturePad.java:270)
                                                          at com.github.gcacace.signaturepad.views.SignaturePad.onTouchEvent(SignaturePad.java:163)
                                                          at android.view.View.dispatchTouchEvent(View.java:7714)
                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
                                                          at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2068)
                                                          at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1515)
                                                          at android.app.Activity.dispatchTouchEvent(Activity.java:2475)
                                                          at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:67)
                                                          at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2016)
                                                          at android.view.View.dispatchPointerEvent(View.java:7894)
                                                          at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:3995)
                                                          at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3874)
                                                          at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3435)
                                                          at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3485)
                                                          at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3454)
                                                          at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3561)
                                                          at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3462)
                                                          at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3618)
                                                          at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3435)
                                                          at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3485)
                                                          at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3454)
                                                          at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3462)
                                                          at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3435)
                                                          at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5580)
                                                          at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5560)
                                                          at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5531)
                                                          at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5660)
                                                          at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                          at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
                                                          at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
                                                          at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:5633)
                                                          at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:5679)
                                                          at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
                                                          at android.view.Choreographer.doCallbacks(Choreographer.java:574)
                                                          at android.view.Choreographer.doFrame(Choreographer.java:542)

**Comment by dskrvk** [comment] 2018-09-17 19:42
Duplicate of https://github.com/gcacace/android-signaturepad/issues/49 ?

**Closed** 2021-09-29 14:04 UTC
