### ISSUE TITLE
TransactionTooLargeException: data parcel size 1991100 bytes

### ISSUE THREAD

**Issue by Arunkrishna008** [gcacace/android-signaturepad#97] opened 2017-10-10 09:51 UTC
hai,

i got an error when i minimize the app

j
![capture](https://user-images.githubusercontent.com/14347412/31380283-86a640b4-adce-11e7-97fc-5874992d94b4.JPG)

**Comment by tplive** [comment] 2018-01-05 14:43
This explains the error: https://developer.android.com/reference/android/os/TransactionTooLargeException.html
In your error message the parcel is 1,99 MB while the Binder buffer is max 1 MB as per the documentation. I'd guess that you are trying to store the signature bitmap in a parcel object in your app..?

**Comment by gcacace** [comment] 2021-09-29 14:04
Duplicate of #49

**Closed by gcacace** 2021-09-29 14:04 UTC
